import './globals.css'
import { Provider } from 'react-redux'
// import { Store } from 'redux'
import {store} from './undo/store';
import { Providers } from './provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <html>
      <head/>
      <body>
       <Providers>
        {children}
        </Providers>
      </body>
      </html>
  )
}
